blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/joshsmithxrm/power-platform-developer-suite/discussions
    about: Please use GitHub Discussions for questions
